# docker-compose.yml

networks:
  network:
    driver: bridge

services:

  database:
    image: postgres:16.9
    networks: [network]
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "axu"
      POSTGRES_PASSWORD: "kakskasi"
      # POSTGRES_HOST_AUTH_METHOD: "trust"  # not needed if using a password

 