# docker-compose.yml

networks:
  network:
    driver: bridge

services:
  nginx: 
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - directus
    networks: [network]

  database:
    image: postgres:16.9
    networks: [network]
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "axu"
      POSTGRES_PASSWORD: "kakskasi"
      # POSTGRES_HOST_AUTH_METHOD: "trust"  # not needed if using a password

  directus:
    image: directus/directus:11.10.2
    networks: [network]
    container_name: directus
    restart: always
    ports:
      - "8055:8055"
    volumes:
      - ./apps/admin/uploads:/directus/uploads:Z
      - ./apps/admin/extensions:/directus/extensions:Z
    depends_on:
      - database
      - cache
    environment:
      SECRET: "titty"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "postgres"
      DB_USER: "axu"           # <-- was "postgres", must match POSTGRES_USER
      DB_PASSWORD: "kakskasi"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "alex@muuttokone.fi"
      ADMIN_PASSWORD: "titty"

      PUBLIC_URL: "http://localhost:8055"
      DIRECTUS_PUBLIC_URL: "http://localhost:8055"
      DIRECTUS_ADMIN_EMAIL: "alex@muuttokone.fi"
      DIRECTUS_ADMIN_PASSWORD: "titty"