steps:
  # 1. Build and Push using Kaniko for extreme caching
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$_TAG
      - --cache=true
      - --cache-ttl=168h
      - --build-arg=NEXT_PUBLIC_GA_ID=$_NEXT_PUBLIC_GA_ID
      - --build-arg=NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY

  # 2. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$_TAG'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'

substitutions:
  _REGION: europe-north1
  _REPO_NAME: muuttokone
  _SERVICE_NAME: muuttokone
  _TAG: latest
  _NEXT_PUBLIC_GA_ID: ""
  _NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ""
