allowBuilds:
  '@prisma/client': set this to true or false
  "@prisma/engines": true
  '@tailwindcss/oxide': set this to true or false
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
